### PR TITLE
fix: Error at return last reserved value

### PR DESCRIPTION
**Pull request by nigma143**
https://github.com/adamsky/id-pool/issues/2

### CODE REVIEW

**Review by adamsky — APPROVED** [review]
Nice catch @nigma143, thanks!

**Comment by kyp44** [comment]
@adamsky are you able to cut a new patch version (0.2.2)  and release it on crates.io?

**Comment by adamsky** [comment]
@kyp44 done!

**Comment by kyp44** [comment]
Thanks Adam, and thanks for the crate, it's super useful for a project I'm working on!

**Pull request merged**
